name = "bar-menu"
main = "src/index.js"
compatibility_date = "2026-10-04"

[[routes]]
pattern = "shulya.party"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "bar-menu-db"
database_id = "370d49fa-99b0-4497-861e-db1a77a710a0"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "bar-menu-photos"
